[options]

ENTITY_REF=Entity Ref

FILE_PATH = FullName

UPLOAD_TYPE=Upload type
DOCUMENT_TYPE=Document type
TITLE_FIELD=Title
DESCRIPTION_FIELD=Description
SECURITY_FIELD=Security
RETENTION_FIELD=Retention Policy
MOVETO_FIELD=Move to
DELETE_FIELD=Delete
IDENTIFIER_FIELD=Identifier
IDENTIFIER_DEFAULT=code

PAX_PATH=PAX Path
PAX_PRES_FIELD=Preservation
PAX_ACCESS_FIELD=Access

ARCREF_FIELD=Archive_Reference
ACCREF_FIELD=Accession_Reference
ACCREF_CODE=accref